# Generated by Django 2.2.7 on 2019-11-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
            options={
                'db_table': 'produtos',
            },
        ),
    ]
