# Generated by Django 2.2.7 on 2019-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_itens', models.IntegerField()),
                ('datahora', models.DateTimeField()),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('altura', models.CharField(max_length=200)),
                ('valorTotal', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
            options={
                'db_table': 'vendas',
            },
        ),
    ]
